# Decision Tree Regression

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
dataset=pd.read_excel('dataset.xlsx','Bowlers')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [15]:
X

array([[ 47.  ,  25.  ,  14.72,   7.82,  11.28],
       [ 64.3 ,  22.  ,  21.9 ,   7.47,  17.59],
       [ 48.  ,  20.  ,  17.35,   7.22,  14.4 ],
       [ 61.4 ,  19.  ,  21.52,   6.63,  19.47],
       [ 34.5 ,  19.  ,  15.1 ,   8.23,  11.  ],
       [ 54.  ,  19.  ,  24.68,   8.68,  17.05],
       [ 49.2 ,  18.  ,  21.44,   7.82,  16.44],
       [ 60.  ,  17.  ,  22.17,   6.28,  21.17],
       [ 44.  ,  16.  ,  19.5 ,   7.09,  16.5 ],
       [ 44.5 ,  16.  ,  27.37,   9.76,  16.81],
       [ 54.  ,  15.  ,  22.86,   6.35,  21.6 ],
       [ 55.  ,  15.  ,  26.66,   7.27,  22.  ],
       [ 42.3 ,  14.  ,  27.85,   9.17,  18.21],
       [ 47.  ,  13.  ,  23.69,   6.55,  21.69],
       [ 46.  ,  13.  ,  26.84,   7.58,  21.23],
       [ 59.  ,  13.  ,  35.46,   7.81,  27.23],
       [ 33.  ,  13.  ,  23.53,   9.27,  15.23],
       [ 46.  ,  12.  ,  27.91,   7.28,  23.  ],
       [ 42.4 ,  12.  ,  29.33,   8.25,  21.33],
       [ 40.  ,  11.  ,  24.54,   6.75,  21.81],
       [ 43.  ,  11.

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
X

array([[ 47.  ,  25.  ,  14.72,   7.82,  11.28],
       [ 64.3 ,  22.  ,  21.9 ,   7.47,  17.59],
       [ 48.  ,  20.  ,  17.35,   7.22,  14.4 ],
       [ 61.4 ,  19.  ,  21.52,   6.63,  19.47],
       [ 34.5 ,  19.  ,  15.1 ,   8.23,  11.  ],
       [ 54.  ,  19.  ,  24.68,   8.68,  17.05],
       [ 49.2 ,  18.  ,  21.44,   7.82,  16.44],
       [ 60.  ,  17.  ,  22.17,   6.28,  21.17],
       [ 44.  ,  16.  ,  19.5 ,   7.09,  16.5 ],
       [ 44.5 ,  16.  ,  27.37,   9.76,  16.81],
       [ 54.  ,  15.  ,  22.86,   6.35,  21.6 ],
       [ 55.  ,  15.  ,  26.66,   7.27,  22.  ],
       [ 42.3 ,  14.  ,  27.85,   9.17,  18.21],
       [ 47.  ,  13.  ,  23.69,   6.55,  21.69],
       [ 46.  ,  13.  ,  26.84,   7.58,  21.23],
       [ 59.  ,  13.  ,  35.46,   7.81,  27.23],
       [ 33.  ,  13.  ,  23.53,   9.27,  15.23],
       [ 46.  ,  12.  ,  27.91,   7.28,  23.  ],
       [ 42.4 ,  12.  ,  29.33,   8.25,  21.33],
       [ 40.  ,  11.  ,  24.54,   6.75,  21.81],
       [ 43.  ,  11.

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [19]:
X_train.shape

(82, 5)

In [20]:
y_train.shape

(82,)

In [21]:
y_pred = regressor.predict(X_test)

In [22]:
y_pred

array([850.,  50., 720.,   0.,  20.,   0., 700.,   0.,   0.,   0.,   0.,
         0.,  20., 720., 700.,  50., 850., 850., 380., 720., 320.])

In [23]:
from sklearn.metrics import mean_squared_error,r2_score
#The mean squared error
print('Mean squared error: %.2f'% mean_squared_error(y_test,y_pred))
print('Coefficient of determination: %.2f'% r2_score(y_test, y_pred))

Mean squared error: 113433.33
Coefficient of determination: -1.01
