In [16]:
import numpy as np
import pandas as pd

In [17]:
dataset=pd.read_excel('../final_dataset_merged_v2.xlsx','Bowlers')


In [18]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [19]:
X

array([[ 49.15,  17.5 ,  26.76,   7.36,  21.42],
       [ 47.85,  17.5 ,  28.8 ,   8.34,  19.45],
       [ 56.6 ,  18.5 ,  21.91,   7.13,  18.43],
       [ 47.  ,  16.5 ,  25.2 ,   8.84,  17.09],
       [ 33.7 ,  12.  ,  25.91,   8.47,  18.16],
       [ 61.  ,  19.  ,  21.43,   6.68,  19.23],
       [ 46.  ,  14.5 ,  25.58,   7.92,  19.47],
       [ 50.7 ,  18.5 ,  22.5 ,   8.15,  16.53],
       [ 31.1 ,  12.5 ,  23.23,   9.56,  14.63],
       [ 18.05,   8.5 ,  30.66,   9.19,  18.03],
       [ 50.7 ,  18.5 ,  22.39,   8.34,  16.11],
       [ 37.  ,   9.  ,  48.4 ,   7.96,  35.6 ],
       [ 46.65,  13.  ,  27.02,   7.46,  21.82],
       [ 19.85,   8.5 ,  19.36,   8.16,  14.2 ],
       [ 37.4 ,  10.  ,  38.77,   9.91,  23.25],
       [ 38.5 ,  18.  ,  15.21,   7.36,  12.25],
       [ 40.5 ,  10.  ,  32.1 ,   7.68,  24.88],
       [ 22.5 ,   7.5 ,  33.83,   8.98,  21.75],
       [ 46.1 ,  14.5 ,  26.45,   8.21,  19.3 ],
       [ 25.75,   7.5 ,  26.17,   7.99,  19.78],
       [ 42.25,  13.

In [20]:
y

array([ 850,  840,  700,  100,  100,  900,  300,  420,    0,  100,  380,
        500,  600,  500,  500,  720, 1250,  710,  580,    0,  260,   95,
        880,  850,  400,  260,  320,  200,    0,    0,  320, 1100,  420,
        220,  400,  700,  480,    0,  300,   50,  220,  300,   75,  100,
          0,   20,  100,   50,    0,  620,  360,   70,    0,  220,  190,
         80,  100,  500,  200,    0,    0,  340,    0], dtype=int64)

In [21]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
X

array([[ 49.15,  17.5 ,  26.76,   7.36,  21.42],
       [ 47.85,  17.5 ,  28.8 ,   8.34,  19.45],
       [ 56.6 ,  18.5 ,  21.91,   7.13,  18.43],
       [ 47.  ,  16.5 ,  25.2 ,   8.84,  17.09],
       [ 33.7 ,  12.  ,  25.91,   8.47,  18.16],
       [ 61.  ,  19.  ,  21.43,   6.68,  19.23],
       [ 46.  ,  14.5 ,  25.58,   7.92,  19.47],
       [ 50.7 ,  18.5 ,  22.5 ,   8.15,  16.53],
       [ 31.1 ,  12.5 ,  23.23,   9.56,  14.63],
       [ 18.05,   8.5 ,  30.66,   9.19,  18.03],
       [ 50.7 ,  18.5 ,  22.39,   8.34,  16.11],
       [ 37.  ,   9.  ,  48.4 ,   7.96,  35.6 ],
       [ 46.65,  13.  ,  27.02,   7.46,  21.82],
       [ 19.85,   8.5 ,  19.36,   8.16,  14.2 ],
       [ 37.4 ,  10.  ,  38.77,   9.91,  23.25],
       [ 38.5 ,  18.  ,  15.21,   7.36,  12.25],
       [ 40.5 ,  10.  ,  32.1 ,   7.68,  24.88],
       [ 22.5 ,   7.5 ,  33.83,   8.98,  21.75],
       [ 46.1 ,  14.5 ,  26.45,   8.21,  19.3 ],
       [ 25.75,   7.5 ,  26.17,   7.99,  19.78],
       [ 42.25,  13.

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [23]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [24]:
# X_test
# [9.75e+02, 6.82e+02, 2.44e+01, 1.43e+02]
# regressor.predict([[9.75e+02, 6.82e+02, 2.44e+01, 1.43e+02]])

In [25]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[280.16 100.  ]
 [120.49 620.  ]
 [-69.92   0.  ]
 [252.69  70.  ]
 [429.47 420.  ]
 [369.94 400.  ]
 [320.87   0.  ]
 [299.06 100.  ]
 [533.68 500.  ]
 [695.58 700.  ]
 [395.39 320.  ]
 [  9.52   0.  ]
 [421.59 100.  ]]


In [26]:
y_test

array([100, 620,   0,  70, 420, 400,   0, 100, 500, 700, 320,   0, 100],
      dtype=int64)

In [27]:
from sklearn.metrics import mean_squared_error,r2_score
print('Coefficients: \n', regressor.coef_)
# The mean squared error
print('Mean squared error: %.2f'% mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'% r2_score(y_test, y_pred))

Coefficients: 
 [  9.39  -0.75  -5.85 -27.98  11.25]
Mean squared error: 44165.71
Coefficient of determination: 0.23
