In [13]:
import numpy as np
import pandas as pd

In [14]:
batsmen_df=pd.read_excel('final_dataset_2019_v2.xlsx','Bowlers')

In [15]:
X = batsmen_df.iloc[:, 1:-1].values
y = batsmen_df.iloc[:, -1].values

In [16]:
X

array([[ 47.  ,  25.  ,  14.72,   7.82,  11.28],
       [ 64.3 ,  22.  ,  21.9 ,   7.47,  17.59],
       [ 48.  ,  20.  ,  17.35,   7.22,  14.4 ],
       [ 61.4 ,  19.  ,  21.52,   6.63,  19.47],
       [ 34.5 ,  19.  ,  15.1 ,   8.23,  11.  ],
       [ 54.  ,  19.  ,  24.68,   8.68,  17.05],
       [ 49.2 ,  18.  ,  21.44,   7.82,  16.44],
       [ 60.  ,  17.  ,  22.17,   6.28,  21.17],
       [ 44.  ,  16.  ,  19.5 ,   7.09,  16.5 ],
       [ 44.5 ,  16.  ,  27.37,   9.76,  16.81],
       [ 54.  ,  15.  ,  22.86,   6.35,  21.6 ],
       [ 55.  ,  15.  ,  26.66,   7.27,  22.  ],
       [ 42.3 ,  14.  ,  27.85,   9.17,  18.21],
       [ 47.  ,  13.  ,  23.69,   6.55,  21.69],
       [ 46.  ,  13.  ,  26.84,   7.58,  21.23],
       [ 59.  ,  13.  ,  35.46,   7.81,  27.23],
       [ 33.  ,  13.  ,  23.53,   9.27,  15.23],
       [ 46.  ,  12.  ,  27.91,   7.28,  23.  ],
       [ 42.4 ,  12.  ,  29.33,   8.25,  21.33],
       [ 40.  ,  11.  ,  24.54,   6.75,  21.81],
       [ 43.  ,  11.

In [17]:
y

array([ 420,   80,   20,  700,  300,  480,  600,  900,  200,  200,  700,
        760, 1100,  190,  110,  850,  710,  880,  300,  400,  720,  640,
        300,  700,  500,  850,  420,  720,  840,    0,  100,   20,  260,
        420,    0,  260,    0,  170,  380,   75,    0, 1250,    0,    0,
        220,  150,   50,  320,    0,  580,   20,   50,  240,  100,  340,
        100,  300,  400,  720,    0,  300,    0,    0,    0,  620,  200,
          0,   20,  320,  160,   20,   50,    0,  620,    0,  320,  500,
         85,   20,  360,   55,    0,  500,    0,  100,  220,  500, 1100,
        190,  200,   95,    0,  500,   70,    0,  220,  340,    0,  140,
         20,    0,    0,   25], dtype=int64)

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
X

array([[ 47.  ,  25.  ,  14.72,   7.82,  11.28],
       [ 64.3 ,  22.  ,  21.9 ,   7.47,  17.59],
       [ 48.  ,  20.  ,  17.35,   7.22,  14.4 ],
       [ 61.4 ,  19.  ,  21.52,   6.63,  19.47],
       [ 34.5 ,  19.  ,  15.1 ,   8.23,  11.  ],
       [ 54.  ,  19.  ,  24.68,   8.68,  17.05],
       [ 49.2 ,  18.  ,  21.44,   7.82,  16.44],
       [ 60.  ,  17.  ,  22.17,   6.28,  21.17],
       [ 44.  ,  16.  ,  19.5 ,   7.09,  16.5 ],
       [ 44.5 ,  16.  ,  27.37,   9.76,  16.81],
       [ 54.  ,  15.  ,  22.86,   6.35,  21.6 ],
       [ 55.  ,  15.  ,  26.66,   7.27,  22.  ],
       [ 42.3 ,  14.  ,  27.85,   9.17,  18.21],
       [ 47.  ,  13.  ,  23.69,   6.55,  21.69],
       [ 46.  ,  13.  ,  26.84,   7.58,  21.23],
       [ 59.  ,  13.  ,  35.46,   7.81,  27.23],
       [ 33.  ,  13.  ,  23.53,   9.27,  15.23],
       [ 46.  ,  12.  ,  27.91,   7.28,  23.  ],
       [ 42.4 ,  12.  ,  29.33,   8.25,  21.33],
       [ 40.  ,  11.  ,  24.54,   6.75,  21.81],
       [ 43.  ,  11.

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [20]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [21]:
# X_test
# [9.75e+02, 6.82e+02, 2.44e+01, 1.43e+02]
# regressor.predict([[9.75e+02, 6.82e+02, 2.44e+01, 1.43e+02]])

In [22]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[507.03 420.  ]
 [189.6  300.  ]
 [490.42  20.  ]
 [184.24  50.  ]
 [115.22  50.  ]
 [160.57 500.  ]
 [376.74 710.  ]
 [196.78   0.  ]
 [267.81 300.  ]
 [199.09   0.  ]
 [198.81 340.  ]
 [169.93 220.  ]
 [ 95.95 140.  ]
 [515.4  190.  ]
 [620.16 900.  ]
 [369.   100.  ]
 [534.47 300.  ]
 [554.66 500.  ]
 [456.46 420.  ]
 [475.86 200.  ]
 [218.28   0.  ]]


In [23]:
y_test

array([420, 300,  20,  50,  50, 500, 710,   0, 300,   0, 340, 220, 140,
       190, 900, 100, 300, 500, 420, 200,   0], dtype=int64)

In [24]:
from sklearn.metrics import mean_squared_error,r2_score
print('Coefficients: \n', regressor.coef_)
# The mean squared error
print('Mean squared error: %.2f'% mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'% r2_score(y_test, y_pred))

Coefficients: 
 [ 10.47  -8.31   6.05 -21.29 -10.33]
Mean squared error: 49189.38
Coefficient of determination: 0.13
