In [14]:
import numpy as np
import pandas as pd

In [15]:
dataset=pd.read_excel('final_dataset_2019_v2.xlsx','Batsmen')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [16]:
dataset.head(5)

Player  Inns  NO  Runs    Avg   BF      SR  Price
0     David Warner    12   2   692  69.20  481  143.86   1200
1         KL Rahul    14   3   593  53.90  438  135.38   1100
2  Quinton de Kock    16   1   529  35.26  398  132.91    280
3   Shikhar Dhawan    16   1   521  34.73  384  135.67    520
4    Andre Russell    13   4   510  56.66  249  204.81    700

In [17]:
X

array([[1.2000e+01, 2.0000e+00, 6.9200e+02, 6.9200e+01, 4.8100e+02,
        1.4386e+02],
       [1.4000e+01, 3.0000e+00, 5.9300e+02, 5.3900e+01, 4.3800e+02,
        1.3538e+02],
       [1.6000e+01, 1.0000e+00, 5.2900e+02, 3.5260e+01, 3.9800e+02,
        1.3291e+02],
       [1.6000e+01, 1.0000e+00, 5.2100e+02, 3.4730e+01, 3.8400e+02,
        1.3567e+02],
       [1.3000e+01, 4.0000e+00, 5.1000e+02, 5.6660e+01, 2.4900e+02,
        2.0481e+02],
       [1.3000e+01, 1.0000e+00, 4.9000e+02, 4.0830e+01, 3.1900e+02,
        1.5360e+02],
       [1.6000e+01, 3.0000e+00, 4.8800e+02, 3.7530e+01, 3.0000e+02,
        1.6266e+02],
       [1.4000e+01, 0.0000e+00, 4.6400e+02, 3.3140e+01, 3.2800e+02,
        1.4146e+02],
       [1.6000e+01, 1.0000e+00, 4.6300e+02, 3.0860e+01, 3.8600e+02,
        1.1994e+02],
       [1.0000e+01, 2.0000e+00, 4.4500e+02, 5.5620e+01, 2.8300e+02,
        1.5724e+02],
       [1.3000e+01, 3.0000e+00, 4.4200e+02, 4.4200e+01, 2.8700e+02,
        1.5400e+02],
       [1.5000e+01, 2

In [18]:
y

array([1200, 1100,  280,  520,  700,  200,  800, 1700,  700,  220, 1100,
        320,    0,  960, 1500, 1100,  400,  160,  400, 1100,  170,  120,
       1100,  340,  800,  100, 1200,  440,  180,  220,  640,  540,  740,
        320,  170,  300,  620,  640,  880,   25,  420,  140,  780,    0,
        300,  850,  340, 1250,  100,  500,  700,  620,    0,    0,  720,
        420,  120,  190,    0,  640,    0,    0,   50,  720,  360,  200,
         20,    0,  380,  220,  420,  760,  500,  190,   80,  900,  710,
         50,  300,  420,  400,    0,    0,    0,  220,  620,    0,    0,
         20,  260,  420,  850,  580,  190,  100,  500,  110,  200,  100,
        100,   55,   50,    0,   20,   80,  220,    0,   20,  600,  300,
         20,   50,    0,    0,  560,   20,   75,  260,  200,   70,    0,
          0,  240,    0,  340,  300,  200,    0,  320,   95,  480,  840,
        380,   20,  700,  720,   20,   20,  500,    0,  300,  100,    0,
        400], dtype=int64)

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
X

array([[1.2000e+01, 2.0000e+00, 6.9200e+02, 6.9200e+01, 4.8100e+02,
        1.4386e+02],
       [1.4000e+01, 3.0000e+00, 5.9300e+02, 5.3900e+01, 4.3800e+02,
        1.3538e+02],
       [1.6000e+01, 1.0000e+00, 5.2900e+02, 3.5260e+01, 3.9800e+02,
        1.3291e+02],
       [1.6000e+01, 1.0000e+00, 5.2100e+02, 3.4730e+01, 3.8400e+02,
        1.3567e+02],
       [1.3000e+01, 4.0000e+00, 5.1000e+02, 5.6660e+01, 2.4900e+02,
        2.0481e+02],
       [1.3000e+01, 1.0000e+00, 4.9000e+02, 4.0830e+01, 3.1900e+02,
        1.5360e+02],
       [1.6000e+01, 3.0000e+00, 4.8800e+02, 3.7530e+01, 3.0000e+02,
        1.6266e+02],
       [1.4000e+01, 0.0000e+00, 4.6400e+02, 3.3140e+01, 3.2800e+02,
        1.4146e+02],
       [1.6000e+01, 1.0000e+00, 4.6300e+02, 3.0860e+01, 3.8600e+02,
        1.1994e+02],
       [1.0000e+01, 2.0000e+00, 4.4500e+02, 5.5620e+01, 2.8300e+02,
        1.5724e+02],
       [1.3000e+01, 3.0000e+00, 4.4200e+02, 4.4200e+01, 2.8700e+02,
        1.5400e+02],
       [1.5000e+01, 2

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [21]:
X_train.shape

(115, 6)

In [22]:
y_train.shape

(115,)

In [23]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y_train)

LinearRegression()

In [24]:
from sklearn.metrics import mean_squared_error,r2_score
y_pred=lin_reg_2.predict(poly_reg.fit_transform(X_test))
# The mean squared error
print('Mean squared error: %.2f'% mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'% r2_score(y_test, y_pred))

Mean squared error: 198989.08
Coefficient of determination: -0.18
