In [12]:
import numpy as np
import pandas as pd

In [13]:
dataset=pd.read_excel('../final_dataset_merged_v2.xlsx','Bowlers')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [14]:
dataset.head(5)

Player     Ov  Wkts     Avg   Econ      SR  Price
0     Bhuvneshwar Kumar  49.15  17.5  26.760  7.355  21.420    850
1        Jaydev Unadkat  47.85  17.5  28.795  8.335  19.450    840
2        Jasprit Bumrah  56.60  18.5  21.915  7.135  18.425    700
3  Mitchell McClenaghan  47.00  16.5  25.195  8.840  17.095    100
4           Imran Tahir  33.70  12.0  25.915  8.470  18.160    100

In [15]:
X

array([[ 49.15 ,  17.5  ,  26.76 ,   7.355,  21.42 ],
       [ 47.85 ,  17.5  ,  28.795,   8.335,  19.45 ],
       [ 56.6  ,  18.5  ,  21.915,   7.135,  18.425],
       [ 47.   ,  16.5  ,  25.195,   8.84 ,  17.095],
       [ 33.7  ,  12.   ,  25.915,   8.47 ,  18.16 ],
       [ 61.   ,  19.   ,  21.425,   6.675,  19.235],
       [ 46.   ,  14.5  ,  25.58 ,   7.925,  19.47 ],
       [ 50.7  ,  18.5  ,  22.505,   8.155,  16.53 ],
       [ 31.1  ,  12.5  ,  23.225,   9.565,  14.635],
       [ 18.05 ,   8.5  ,  30.655,   9.185,  18.03 ],
       [ 50.7  ,  18.5  ,  22.395,   8.345,  16.11 ],
       [ 37.   ,   9.   ,  48.395,   7.96 ,  35.6  ],
       [ 46.65 ,  13.   ,  27.015,   7.455,  21.82 ],
       [ 19.85 ,   8.5  ,  19.355,   8.165,  14.2  ],
       [ 37.4  ,  10.   ,  38.765,   9.91 ,  23.245],
       [ 38.5  ,  18.   ,  15.205,   7.355,  12.25 ],
       [ 40.5  ,  10.   ,  32.1  ,   7.68 ,  24.875],
       [ 22.5  ,   7.5  ,  33.83 ,   8.975,  21.75 ],
       [ 46.1  ,  14.5  ,  2

In [16]:
y

array([ 850,  840,  700,  100,  100,  900,  300,  420,    0,  100,  380,
        500,  600,  500,  500,  720, 1250,  710,  580,    0,  260,   95,
        880,  850,  400,  260,  320,  200,    0,    0,  320, 1100,  420,
        220,  400,  700,  480,    0,  300,   50,  220,  300,   75,  100,
          0,   20,  100,   50,    0,  620,  360,   70,    0,  220,  190,
         80,  100,  500,  200,    0,    0,  340,    0], dtype=int64)

In [17]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])
X

array([[ 49.15 ,  17.5  ,  26.76 ,   7.355,  21.42 ],
       [ 47.85 ,  17.5  ,  28.795,   8.335,  19.45 ],
       [ 56.6  ,  18.5  ,  21.915,   7.135,  18.425],
       [ 47.   ,  16.5  ,  25.195,   8.84 ,  17.095],
       [ 33.7  ,  12.   ,  25.915,   8.47 ,  18.16 ],
       [ 61.   ,  19.   ,  21.425,   6.675,  19.235],
       [ 46.   ,  14.5  ,  25.58 ,   7.925,  19.47 ],
       [ 50.7  ,  18.5  ,  22.505,   8.155,  16.53 ],
       [ 31.1  ,  12.5  ,  23.225,   9.565,  14.635],
       [ 18.05 ,   8.5  ,  30.655,   9.185,  18.03 ],
       [ 50.7  ,  18.5  ,  22.395,   8.345,  16.11 ],
       [ 37.   ,   9.   ,  48.395,   7.96 ,  35.6  ],
       [ 46.65 ,  13.   ,  27.015,   7.455,  21.82 ],
       [ 19.85 ,   8.5  ,  19.355,   8.165,  14.2  ],
       [ 37.4  ,  10.   ,  38.765,   9.91 ,  23.245],
       [ 38.5  ,  18.   ,  15.205,   7.355,  12.25 ],
       [ 40.5  ,  10.   ,  32.1  ,   7.68 ,  24.875],
       [ 22.5  ,   7.5  ,  33.83 ,   8.975,  21.75 ],
       [ 46.1  ,  14.5  ,  2

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [19]:
X_train.shape

(50, 5)

In [20]:
y_train.shape

(50,)

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 2)
X_poly = poly_reg.fit_transform(X_train)
lin_reg_2 = LinearRegression()
lin_reg_2.fit(X_poly, y_train)

LinearRegression()

In [22]:
from sklearn.metrics import mean_squared_error,r2_score
y_pred=lin_reg_2.predict(poly_reg.fit_transform(X_test))
# The mean squared error
print('Mean squared error: %.2f'% mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'% r2_score(y_test, y_pred))

Mean squared error: 60207.73
Coefficient of determination: -0.05
